class MutConstants():

    def __init__(self):
        self.chr_list = ['chr1', 'chr2', 'chr3', 'chr4',
                         'chr5', 'chr6', 'chr7', 'chr8',
                         'chr9', 'chr10', 'chr11', 'chr12',
                         'chr13', 'chr14', 'chr15', 'chr16',
                         'chr17', 'chr18', 'chr19', 'chr20',
                         'chr21', 'chr22']
        self.name_to_colname_example_dict = {
            'Gorilla': 'gorilla',
            'Orang': 'orang',
            'Chimp': 'chimp',
            'Bonobo': 'bonobo',
            'Human': 'human',
            'Gorilla_P': 'gorilla_P',
            'Orang_P': 'orang_P',
            'Chimp_P': 'chimp_P',
            'Bonobo_P': 'bonobo_P',
            'Human_P': 'human_P'}
        self.subs192 = ['A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C',
                        'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C',
                        'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G',
                        'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G',
                        'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T',
                        'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T',
                        'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A',
                        'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A',
                        'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G',
                        'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G',
                        'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T',
                        'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T',
                        'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A',
                        'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A',
                        'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C',
                        'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C',
                        'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T',
                        'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T',
                        'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A',
                        'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A',
                        'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C',
                        'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C',
                        'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G',
                        'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G']
        self.context192 = ['A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G',
                           'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C',
                           'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A',
                           'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T',
                           'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G',
                           'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C',
                           'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A',
                           'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T',
                           'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G',
                           'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C',
                           'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A',
                           'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T',
                           'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G',
                           'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C',
                           'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A',
                           'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T',
                           'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G',
                           'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C',
                           'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A',
                           'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T',
                           'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G',
                           'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C',
                           'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A',
                           'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T',
                           'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G',
                           'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C',
                           'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A',
                           'T.C', 'T.G', 'T.T']
        self.pictures_pol_example = [
            [['Human_P', 'Chimp_P'],
             ['Human_P', 'Orang_P'],
             ['Chimp_P', 'Orang_P'],
             ['Bonobo_P', 'Orang_P'],
             ['Gorilla_P', 'Orang_P']],

            [['Human_P', 'Chimp_P'],
             ['Bonobo_P', 'Chimp_P'],
             ['Gorilla_P', 'Chimp_P'],
             ['Orang_P', 'Chimp_P']],

            [['Human_P', 'Gorilla_P'],
             ['Chimp_P', 'Gorilla_P'],
             ['Bonobo_P', 'Gorilla_P'],
             ['Orang_P', 'Gorilla_P']],

            [['Human_P', 'Bonobo_P'],
             ['Chimp_P', 'Bonobo_P'],
             ['Gorilla_P', 'Bonobo_P'],
             ['Orang_P', 'Bonobo_P']]
        ]
        self.pictures_div_example = [
            [['Human', 'Chimp'],
             ['Human', 'Orang'],
             ['Chimp', 'Orang'],
             ['Bonobo', 'Orang'],
             ['Gorilla', 'Orang']],

            [['Human', 'Chimp'],
             ['Bonobo', 'Chimp'],
             ['Gorilla', 'Chimp'],
             ['Orang', 'Chimp']],

            [['Human', 'Gorilla'],
             ['Chimp', 'Gorilla'],
             ['Bonobo', 'Gorilla'],
             ['Orang', 'Gorilla']],

            [['Human', 'Bonobo'],
             ['Chimp', 'Bonobo'],
             ['Gorilla', 'Bonobo'],
             ['Orang', 'Bonobo']],

            [['Human', 'Human_P'],
             ['Chimp', 'Chimp_P'],
             ['Bonobo', 'Bonobo_P'],
             ['Gorilla', 'Gorilla_P'],
             ['Orang', 'Orang_P']]
        ]
        self.start_positions_ucsc = {'chr1': 10917,
                                     'chr10': 10803,
                                     'chr11': 60000,
                                     'chr12': 11163,
                                     'chr13': 18172207,
                                     'chr14': 16022637,
                                     'chr15': 19830514,
                                     'chr16': 10000,
                                     'chr17': 60000,
                                     'chr18': 11107,
                                     'chr19': 60000,
                                     'chr2': 11309,
                                     'chr20': 66336,
                                     'chr21': 5010000,
                                     'chr22': 10510000,
                                     'chr3': 11706,
                                     'chr4': 11527,
                                     'chr5': 11282,
                                     'chr6': 60000,
                                     'chr7': 10238,
                                     'chr8': 60000,
                                     'chr9': 10336}
