class MutConstants():

    def __init__(self):
        self.chr_list = ['chr1', 'chr2', 'chr3', 'chr4',
                         'chr5', 'chr6', 'chr7', 'chr8',
                         'chr9', 'chr10', 'chr11', 'chr12',
                         'chr13', 'chr14', 'chr15', 'chr16',
                         'chr17', 'chr18', 'chr19', 'chr20',
                         'chr21', 'chr22']
        self.name_to_colname_example_dict = {
            'Gorilla': 'gorilla',
            'Orang': 'orang',
            'Chimp': 'chimp',
            'Bonobo': 'bonobo',
            'Human': 'human',
            'Gorilla_P': 'gorilla_P',
            'Orang_P': 'orang_P',
            'Chimp_P': 'chimp_P',
            'Bonobo_P': 'bonobo_P',
            'Human_P': 'human_P'}
        self.subs192 = ['A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C',
                        'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C', 'A>C',
                        'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G',
                        'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G', 'A>G',
                        'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T',
                        'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T', 'A>T',
                        'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A',
                        'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A',
                        'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G',
                        'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G',
                        'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T',
                        'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T',
                        'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A',
                        'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A', 'G>A',
                        'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C',
                        'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C', 'G>C',
                        'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T',
                        'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T', 'G>T',
                        'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A',
                        'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A',
                        'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C',
                        'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C',
                        'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G',
                        'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G']
        self.context192 = ['A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G',
                           'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C',
                           'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A',
                           'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T',
                           'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G',
                           'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C',
                           'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A',
                           'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T',
                           'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G',
                           'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C',
                           'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A',
                           'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T',
                           'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G',
                           'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C',
                           'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A',
                           'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T',
                           'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G',
                           'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C',
                           'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A',
                           'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T',
                           'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G',
                           'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C',
                           'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A',
                           'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T',
                           'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G',
                           'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C',
                           'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A',
                           'T.C', 'T.G', 'T.T']
        self.pictures_pol_example = [
            [['Human_P', 'Chimp_P'],
             ['Human_P', 'Orang_P'],
             ['Chimp_P', 'Orang_P'],
             ['Bonobo_P', 'Orang_P'],
             ['Gorilla_P', 'Orang_P']],

            [['Human_P', 'Chimp_P'],
             ['Bonobo_P', 'Chimp_P'],
             ['Gorilla_P', 'Chimp_P'],
             ['Orang_P', 'Chimp_P']],

            [['Human_P', 'Gorilla_P'],
             ['Chimp_P', 'Gorilla_P'],
             ['Bonobo_P', 'Gorilla_P'],
             ['Orang_P', 'Gorilla_P']],

            [['Human_P', 'Bonobo_P'],
             ['Chimp_P', 'Bonobo_P'],
             ['Gorilla_P', 'Bonobo_P'],
             ['Orang_P', 'Bonobo_P']]
        ]
        self.pictures_div_example = [
            [['Human', 'Chimp'],
             ['Human', 'Orang'],
             ['Chimp', 'Orang'],
             ['Bonobo', 'Orang'],
             ['Gorilla', 'Orang']],

            [['Human', 'Chimp'],
             ['Bonobo', 'Chimp'],
             ['Gorilla', 'Chimp'],
             ['Orang', 'Chimp']],

            [['Human', 'Gorilla'],
             ['Chimp', 'Gorilla'],
             ['Bonobo', 'Gorilla'],
             ['Orang', 'Gorilla']],

            [['Human', 'Bonobo'],
             ['Chimp', 'Bonobo'],
             ['Gorilla', 'Bonobo'],
             ['Orang', 'Bonobo']],

            [['Human', 'Human_P'],
             ['Chimp', 'Chimp_P'],
             ['Bonobo', 'Bonobo_P'],
             ['Gorilla', 'Gorilla_P'],
             ['Orang', 'Orang_P']]
        ]
        self.start_positions_ucsc = {'chr1': 10917, 'chr10': 10803,
                                     'chr11': 60000, 'chr12': 11163,
                                     'chr13': 18172207, 'chr14': 16022637,
                                     'chr15': 19830514, 'chr16': 10000,
                                     'chr17': 60000, 'chr18': 11107,
                                     'chr19': 60000, 'chr2': 11309,
                                     'chr20': 66336, 'chr21': 5010000,
                                     'chr22': 10510000, 'chr3': 11706,
                                     'chr4': 11527, 'chr5': 11282,
                                     'chr6': 60000, 'chr7': 10238,
                                     'chr8': 60000, 'chr9': 10336}
        self.ensembl_end_positions = {'chr1': 248941506, 'chr10': 133783350,
                                      'chr11': 135027575, 'chr12': 133234069,
                                      'chr13': 114309972, 'chr14': 106235046,
                                      'chr15': 101978746, 'chr16': 90226324,
                                      'chr17': 83245577, 'chr18': 80242245,
                                      'chr19': 58562207, 'chr2': 242094896,
                                      'chr20': 64267920, 'chr21': 46695402,
                                      'chr22': 50769034, 'chr3': 198222791,
                                      'chr4': 190200648, 'chr5': 181457166,
                                      'chr6': 170730395, 'chr7': 159325434,
                                      'chr8': 145053370, 'chr9': 138331427}
        self.ensembl_start_positions = {'chr1': 12221, 'chr10': 27312,
                                        'chr11': 76057, 'chr12': 48185,
                                        'chr13': 18419910, 'chr14': 18290857,
                                        'chr15': 20005429, 'chr16': 11902,
                                        'chr17': 194652, 'chr18': 164103,
                                        'chr19': 75828, 'chr2': 19390,
                                        'chr20': 94004, 'chr21': 5011874,
                                        'chr22': 10512615, 'chr3': 43656,
                                        'chr4': 29575, 'chr5': 93048,
                                        'chr6': 95325, 'chr7': 157378,
                                        'chr8': 76962, 'chr9': 103290}
        self.context96 = ['A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G',
                          'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C',
                          'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A',
                          'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T',
                          'T.A', 'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G',
                          'A.T', 'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C',
                          'G.G', 'G.T', 'T.A', 'T.C', 'T.G', 'T.T', 'A.A',
                          'A.C', 'A.G', 'A.T', 'C.A', 'C.C', 'C.G', 'C.T',
                          'G.A', 'G.C', 'G.G', 'G.T', 'T.A', 'T.C', 'T.G',
                          'T.T', 'A.A', 'A.C', 'A.G', 'A.T', 'C.A', 'C.C',
                          'C.G', 'C.T', 'G.A', 'G.C', 'G.G', 'G.T', 'T.A',
                          'T.C', 'T.G', 'T.T', 'A.A', 'A.C', 'A.G', 'A.T',
                          'C.A', 'C.C', 'C.G', 'C.T', 'G.A', 'G.C', 'G.G',
                          'G.T', 'T.A', 'T.C', 'T.G', 'T.T']
        self.subs96_common = ['C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A',
                              'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A', 'C>A',
                              'C>A', 'C>A', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G',
                              'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G', 'C>G',
                              'C>G', 'C>G', 'C>G', 'C>G', 'C>T', 'C>T', 'C>T',
                              'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T',
                              'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'C>T', 'T>A',
                              'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A',
                              'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A', 'T>A',
                              'T>A', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C',
                              'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C', 'T>C',
                              'T>C', 'T>C', 'T>C', 'T>G', 'T>G', 'T>G', 'T>G',
                              'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G', 'T>G',
                              'T>G', 'T>G', 'T>G', 'T>G', 'T>G']
        self.subs_context96_common = ['A[C>A]A', 'A[C>A]C', 'A[C>A]G',
                                      'A[C>A]T', 'C[C>A]A', 'C[C>A]C',
                                      'C[C>A]G', 'C[C>A]T', 'G[C>A]A',
                                      'G[C>A]C', 'G[C>A]G', 'G[C>A]T',
                                      'T[C>A]A', 'T[C>A]C', 'T[C>A]G',
                                      'T[C>A]T', 'A[C>G]A', 'A[C>G]C',
                                      'A[C>G]G', 'A[C>G]T', 'C[C>G]A',
                                      'C[C>G]C', 'C[C>G]G', 'C[C>G]T',
                                      'G[C>G]A', 'G[C>G]C', 'G[C>G]G',
                                      'G[C>G]T', 'T[C>G]A', 'T[C>G]C',
                                      'T[C>G]G', 'T[C>G]T', 'A[C>T]A',
                                      'A[C>T]C', 'A[C>T]G', 'A[C>T]T',
                                      'C[C>T]A', 'C[C>T]C', 'C[C>T]G',
                                      'C[C>T]T', 'G[C>T]A', 'G[C>T]C',
                                      'G[C>T]G', 'G[C>T]T', 'T[C>T]A',
                                      'T[C>T]C', 'T[C>T]G', 'T[C>T]T',
                                      'A[T>A]A', 'A[T>A]C', 'A[T>A]G',
                                      'A[T>A]T', 'C[T>A]A', 'C[T>A]C',
                                      'C[T>A]G', 'C[T>A]T', 'G[T>A]A',
                                      'G[T>A]C', 'G[T>A]G', 'G[T>A]T',
                                      'T[T>A]A', 'T[T>A]C', 'T[T>A]G',
                                      'T[T>A]T', 'A[T>C]A', 'A[T>C]C',
                                      'A[T>C]G', 'A[T>C]T', 'C[T>C]A',
                                      'C[T>C]C', 'C[T>C]G', 'C[T>C]T',
                                      'G[T>C]A', 'G[T>C]C', 'G[T>C]G',
                                      'G[T>C]T', 'T[T>C]A', 'T[T>C]C',
                                      'T[T>C]G', 'T[T>C]T', 'A[T>G]A',
                                      'A[T>G]C', 'A[T>G]G', 'A[T>G]T',
                                      'C[T>G]A', 'C[T>G]C', 'C[T>G]G',
                                      'C[T>G]T', 'G[T>G]A', 'G[T>G]C',
                                      'G[T>G]G', 'G[T>G]T', 'T[T>G]A',
                                      'T[T>G]C', 'T[T>G]G', 'T[T>G]T']
